.gitignore, disciplina.cabal, src/Disciplina/Launcher.hs, src/Disciplina/Launcher/Mode.hs, src/Disciplina/Launcher/Params.hs, src/Disciplina/Launcher/Resource.hs, src/Disciplina/Launcher/Runner.hs, src/Main.hs, src/witness/Main.hs, src/witness/Params.hs
=> [TMP-39] Init node launcher structure

src/Disciplina/DB/DSL/Interpret.hs, src/Disciplina/DB/DSL/Types.hs, src/Disciplina/Educator/Txs.hs
=> [DSCP-66] [DSCP-48] Datatype for queries DSL

package.yaml, src/Dscp/Core/Serialise.hs, src/Dscp/Core/Types.hs, src/Dscp/DB/DSL.hs, src/Dscp/DB/DSL/Interpret/SimpleTxDB.hs, src/Dscp/Educator.hs, src/Dscp/Educator/Block.hs, src/Dscp/Educator/Serialise.hs, src/Dscp/Educator/Txs.hs, src/Dscp/Educator/Validate.hs, tests/Test/Common.hs, tests/Test/Dscp/DB/DSL/Interpret/SimpleTxDB.hs, tests/Test/Dscp/Educator/Validate.hs
=> [WIP] [DSCP-100] Pure private blocks validation logic

package.yaml, src/Dscp/Core/Types.hs, src/Dscp/DB/DSL/Interpret/SimpleTxDB.hs, src/Dscp/Educator.hs, src/Dscp/Educator/BlockValidation.hs, src/Dscp/Educator/Txs.hs, src/Dscp/Educator/Validate.hs, tests/Test/Common.hs, tests/Test/Dscp/Educator/BlockValidation.hs, tests/Test/Dscp/Educator/Validate.hs
=> [DSCP-117] validation exceptions structure

hpack/definitions.yaml, src/Dscp/Core.hs, src/Dscp/Educator/BlockValidation.hs, src/Dscp/Listeners/Listener.hs, src/Dscp/Network/Wrapped.hs, src/Dscp/Resource/Logging.hs, src/witness/Main.hs
Looks like I initiated broken window syndrome, fixing it here.
=> Fix warnings

src/Dscp/Resource/Network.hs, stack.yaml
@Martoon-00 pls test, it should be alright now. Actually, before that, zmq context was terminating also, but in 5 seconds (I have no idea where does this number come from).
Relevant change in lootbox:
https://github.com/serokell/lootbox/commit/9b803ba99ce0970766bf5496a855289408daad23
=> [DSCP-131] Properly terminate zmq context

tests/Test/Dscp/Crypto/Instances.hs
=> [DSCP-122] Fix tests

src/Dscp/DB/DSL.hs, src/Dscp/DB/SQLite.hs, src/Dscp/Educator.hs, src/Dscp/Network.hs, src/Dscp/Witness.hs, src/Dscp/Witness/Launcher.hs, tests/Test/Common.hs
"Possible" here means that no item is hidden on purpose.
=> [SRK-8] Get rid of explicit reexports where possible

lib/database/schema.sql, lib/package.yaml, lib/src/Dscp/Core/Aeson.hs, lib/src/Dscp/Core/Types.hs, lib/src/Dscp/DB/SQLite/Class.hs, lib/src/Dscp/DB/SQLite/Instances.hs, lib/src/Dscp/DB/SQLite/Queries.hs, lib/src/Dscp/DB/SQLite/Types.hs, lib/src/Dscp/Educator/BlockValidation.hs, lib/src/Dscp/Educator/Web/Student/API.hs, lib/src/Dscp/Educator/Web/Student/Error.hs, lib/src/Dscp/Educator/Web/Student/Handlers.hs, lib/src/Dscp/Educator/Web/Student/Logic.hs, lib/src/Dscp/Educator/Web/Student/Queries.hs, lib/src/Dscp/Educator/Web/Student/Server.hs, lib/src/Dscp/Educator/Web/Student/Types.hs, lib/src/Dscp/Educator/Web/Student/Util.hs, lib/src/Dscp/Util.hs, lib/tests/Test/Common.hs, lib/tests/Test/Dscp/Core/Instances.hs, lib/tests/Test/Dscp/DB/SQLite/Common.hs, lib/tests/Test/Dscp/DB/SQLite/Queries.hs, lib/tests/Test/Dscp/Educator/Student/Instances.hs, lib/tests/Test/Dscp/Educator/Student/Queries.hs, scripts/launch/node.sh, stack.yaml
Implements student API. Viewing PR on per-commit basis is recommended.
To be done:
=> [DSCP-147] Student queries

lib/package.yaml, lib/src/Dscp/CLI/Common.hs, lib/src/Dscp/Educator/Web/Student/Error.hs
PR consists of parseNetAddr (CLI/Common) reimplementation using parsec and haddock for APIError addition
=> [DSCP-151] Address late comments on Student API stubs

wallet/package.yaml, wallet/src/Dscp/Wallet/Backend.hs, wallet/src/Dscp/Wallet/Face.hs, wallet/src/Dscp/Wallet/Knit.hs
Secret key is now encrypted/decrypted only if passphrase is provided as optional parameter.
=> [AD-313] Make secret key encryption optional

run/log-config.yaml, scripts/launch/node.sh, witness/src/Dscp/Witness/CLI.hs, witness/src/Dscp/Witness/Web/Server.hs
=> [DSCP-152] More renamings (wallet -> witness)

core/src/Dscp/Core/Aeson.hs, core/src/Dscp/Core/Arbitrary.hs, core/src/Dscp/Crypto/Aeson.hs, core/src/Dscp/Util/Aeson.hs, core/tests/Test/Dscp/Util/Serialise.hs, educator/src/Dscp/DB/SQLite/Queries.hs, educator/src/Dscp/Educator/Web/Bot/Handlers.hs, educator/src/Dscp/Educator/Web/Student/API.hs, educator/src/Dscp/Educator/Web/Student/Error.hs, educator/src/Dscp/Educator/Web/Student/Handlers.hs, educator/src/Dscp/Educator/Web/Student/Logic.hs, educator/src/Dscp/Educator/Web/Student/Queries.hs, educator/src/Dscp/Educator/Web/Student/Types.hs, educator/tests/Test/Dscp/Educator/Bot/Endpoints.hs, educator/tests/Test/Dscp/Educator/Student/Queries.hs, specs/disciplina/educator/api/educator.yaml, specs/disciplina/educator/api/student.yaml
I advice to review this on per-commit basis.
=> [DSCP-164] Late fixes in student api

educator/package.yaml, educator/src/Dscp/Educator/CLI.hs, educator/src/Dscp/Educator/Web/Bot/Handlers.hs, educator/src/Dscp/Educator/Web/Bot/Params.hs, educator/src/Dscp/Educator/Web/Bot/Setting.hs, educator/src/Dscp/Educator/Web/Params.hs, educator/src/Dscp/Educator/Web/Server.hs, educator/tests/Test/Dscp/Educator/Bot/Endpoints.hs, scripts/launch/node.sh, witness/package.yaml, witness/src/Dscp/CommonCLI.hs
Now take bot params from CI arguments.
Also improves course names.
=> [DSCP-163] Later fixes in bot

specs/disciplina/witness/api/explorer.yaml
=> [DSCP-172] Swagger spec for Block Explorer API

wallet/src/Dscp/Wallet/Knit.hs
Vty wallet now shows unencrypted secret key for newly generated account.
Both encrypted and unencrypted secret keys are accepted in the Restore form.
=> [DSCP-185] Output and accept unencrypted SKs if no passphrase supplied

educator/src/Dscp/Educator/Web/Server.hs, educator/src/Dscp/Educator/Web/Student/Error.hs
Small fixes which would be nice to have soon
=> Educator API cosmetics

educator/package.yaml, educator/src/Dscp/Educator/Launcher/Mode.hs, educator/src/Dscp/Educator/Web/Bot/Handlers.hs, educator/src/Dscp/Educator/Web/Server.hs, educator/src/Dscp/Educator/Web/Student/API.hs, educator/src/Dscp/Educator/Web/Student/Auth.hs, educator/src/Dscp/Educator/Web/Student/Handlers.hs, educator/tests/Test/Dscp/Educator/Bot/Endpoints.hs, stack.yaml
This PR adds authentication to all students API requests.
The client is supposed to make a signed JWT (http://jwt.io/) and put it into Authorization HTTP header. The JWT should contain only one claim called `dat` and inside it there should be an object with two fields `adTime` and `adPath`. `adTime` should have the time when the request is created. The JWT is considered invalid by the server if server's current time is 5 minutes (or more) ahead of the specified time in JWT (this is to avoid replay attacks). `adPath` should contain the URL path without host as it will be in the raw HTTP request. Example JWT object:
```
{ "dat": {"adTime": "2018-08-10T13:26:59.461998136Z", "adPath":"/api/student/v1/courses"} }
```
Here `dat` is an unregistered JWT claim and the object in it the …
=> [DSCP-141] Add HTTP request signature verification

specs/disciplina/witness/api/explorer.yaml, witness/package.yaml, witness/src/Dscp/Witness/Web/Logic.hs, witness/src/Dscp/Witness/Web/Server.hs, witness/src/Dscp/Witness/Web/Types.hs
=> [DSCP-201] BE API Fixes

stack.yaml, wallet/app-vty/Glue.hs, wallet/app-vty/Main.hs
=> [AD-357] Wallet export

core/package.yaml, core/src/Dscp/Core/Foundation/Witness.hs, core/src/Dscp/Crypto/Signing/Class.hs, core/src/Dscp/Crypto/Signing/Cryptonite.hs, core/src/Dscp/Util.hs, core/src/Dscp/Util/Concurrent.hs, core/src/Dscp/Util/Concurrent/NotifyWait.hs, core/src/Dscp/Util/TimeLimit.hs, faucet/exec/Main.hs, faucet/src/Dscp/Faucet/Web/Logic.hs, specs/disciplina/witness/api/explorer.yaml, wallet/app-vty/Glue.hs, wallet/src/Dscp/Wallet/Backend.hs, wallet/src/Dscp/Wallet/Face.hs, wallet/src/Dscp/Wallet/Knit.hs, witness/src/Dscp/Snowdrop/Mode.hs, witness/src/Dscp/Snowdrop/Types.hs, witness/src/Dscp/Witness/Launcher/Entry.hs, witness/src/Dscp/Witness/Listeners/Listener.hs, witness/src/Dscp/Witness/Logic/Getters.hs, witness/src/Dscp/Witness/Logic/Processing.hs, witness/src/Dscp/Witness/Mempool/Logic.hs, witness/src/Dscp/Witness/Mempool/Type.hs, witness/src/Dscp/Witness/Relay.hs, witness/src/Dscp/Witness/SDLock.hs, witness/src/Dscp/Witness/Web/Error.hs, witness/src/Dscp/Witness/Web/Logic.hs, witness/src/Dscp/Witness/Web/Types.hs, witness/src/Dscp/Witness/Workers/Worker.hs
I advice to review on per-commit basis, each commit has own description.
Also, I wish all the code here to be taken critically (especially in cosmetics), I don't know what I was doing.
Tested:
=> [DSCP-194] Consider mempool everywhere

educator/src/Dscp/Educator/Web/Server.hs
=> [DSCP-210] Add Authorization CORS to student API

educator/src/Dscp/Educator/Web/Auth.hs, educator/src/Dscp/Educator/Web/Educator/API.hs, educator/src/Dscp/Educator/Web/Educator/Auth.hs, educator/src/Dscp/Educator/Web/Server.hs, educator/src/Dscp/Educator/Web/Student/API.hs, specs/disciplina/educator/api/educator.yaml
=>  [DSCP-196] Add Educator authorization check

stack.yaml, wallet/exec-cli/Main.hs, wallet/exec/Glue.hs, wallet/exec/Main.hs, wallet/package.yaml, wallet/src/Dscp/Wallet/Backend.hs, wallet/src/Dscp/Wallet/CLI.hs, wallet/src/Dscp/Wallet/Face.hs, wallet/src/Dscp/Wallet/Knit.hs
DO NOT MERGE before serokell/ariadne#286
=>  [DSCP-220] Transaction history in Vty wallet 

witness/src/Dscp/Snowdrop/Configuration.hs, witness/src/Dscp/Snowdrop/Storage/Pure.hs, witness/src/Dscp/Witness/Logic/Getters.hs, witness/src/Dscp/Witness/Logic/Processing.hs
=> [DSCP-195] Store transaction lists in pure storage instead of AVL

wallet/src/Dscp/Wallet/KeyStorage.hs
See https://serokell.slack.com/archives/CC92X27D3/p1535297402000100
=> [DSCP-226]  Use XDG_DATA_DIR for wallet key storage instead of run/tmp

configuration.yaml, docs/make-test-tx.md, witness/README.md
I'm not very good at docs writing, fell free to comment on style or general story, or even commit changes.
=> [DSCP-223] Add instruction on tx submission

core/src/Dscp/Util.hs, core/src/Dscp/Util/Concurrent/NotifyWait.hs, faucet/src/Dscp/Faucet/Web/Logic.hs, specs/disciplina/witness/api/witness.yaml, wallet/src/Dscp/Wallet/Backend.hs, witness/src/Dscp/Snowdrop/AccountValidation.hs, witness/src/Dscp/Snowdrop/Configuration.hs, witness/src/Dscp/Snowdrop/Mode.hs, witness/src/Dscp/Snowdrop/Types.hs, witness/src/Dscp/Witness/Logic/Exceptions.hs, witness/src/Dscp/Witness/Mempool/Logic.hs, witness/src/Dscp/Witness/Relay.hs, witness/src/Dscp/Witness/Web/API.hs, witness/src/Dscp/Witness/Web/Client/Error.hs, witness/src/Dscp/Witness/Web/Error.hs, witness/src/Dscp/Witness/Web/Handlers.hs, witness/src/Dscp/Witness/Web/Logic.hs, witness/src/Dscp/Witness/Web/Types.hs, witness/src/Dscp/Witness/Web/Util.hs, witness/src/Dscp/Witness/Workers/Worker.hs
=> [DSCP-209] Check account has enough money on witness API side

faucet/frontend/README.md, faucet/frontend/build/webpack.prod.conf.js, faucet/frontend/default.nix, faucet/frontend/src/main.js, witness/frontend/README.md, witness/frontend/build/webpack.prod.conf.js, witness/frontend/default.nix
=> Make frontend API URLs configured by env variables

witness/frontend/src/components/TransactionItem.vue, witness/frontend/src/components/TransactionItem/Money.vue, witness/frontend/src/components/TransactionList.vue, witness/frontend/src/pages/Address.vue
This PR adds font-weight to current address in transactions list. Small change only for UI, not sence to functionality.
=> Set bold address in transactions list if its current

witness/src/Dscp/Witness/Mempool/Logic.hs, witness/src/Dscp/Witness/Workers/Worker.hs
This does not fix original problem, but still may be useful. 
1. Since `checkThenRepublish` is called in several places, it should be made
atomic.
2. Not always exceptions are caught from `checkThenRepublish`.
=> [DSCP-241] Some fixes

configuration.yaml, scripts/launch/node.sh, tools/README.md, tools/singleton-txperf.json, witness/src/Dscp/Resource/Keys/Functions.hs
Makes profiling more convenient.
For profiling report see https://issues.serokell.io/issue/DSCP-249.
=> [DSCP-249] Profile block apply

faucet/exec/Main.hs
In contrast to original purpose this just delivered plenty of inconveniences to
devops team.
=> [DSCP-243] Remove witness backend ping on faucet startup

core/src/Dscp/Util/TimeLimit.hs, educator/src/Dscp/Educator/Launcher/Entry.hs, witness/src/Dscp/Witness/Launcher/Entry.hs, witness/src/Dscp/Witness/SDLock.hs
Some small fixes I dunno how I came to doing this, but this may be helpful.
See on per commit basis, their descriptions are telling.
=> [DSCP-248] General fixes

default.nix
We need a small closure package for copying to the servers. I don't like that this builds everything twice, but what can you do.
=> default.nix: add disciplina-static

docs/config.mb, docs/make-test-tx.md, educator/README.md, scripts/launch/demo.sh, scripts/launch/faucet.sh, scripts/launch/node.sh, witness/README.md
=> Finish renaming configuration.yaml into config.yaml

closure.nix, default.nix, nixpkgs.nix, release.nix
This makes Disciplina fully build in sandbox.
=> Switch to serokell-closure

core/src/Dscp/Util.hs, witness/src/Dscp/Witness/Listeners/Listener.hs, witness/src/Dscp/Witness/Workers/Worker.hs
To make application more resilient to bugs.
=> [DSCP-266] Make workers tolerant to inner errors

docs/authentication.md, educator/src/Dscp/Educator/Web/Auth.hs
I think those should be easily available for everyone.
=> [DSCP-263] Add helper for testing with curl

shell.nix
I've wiped .stack-work clean and currently rebuilding it back inside `nix-shell`.
=> Re-add GHC to shell.nix

config.yaml, core/src/Dscp/Util/Serialise.hs, scripts/launch/node.sh
Let compatibility break one more time!
Tests pass locally.
=> [DSCP-263] Make address encoding correspond CBOR spec

core/src/Dscp/Util/Aeson.hs
Probably some rebase issue, I previously made `nothingToFail` to accept specific `Text`.
=> [SRK-8] Fix master

core/package.yaml, core/src/Dscp/Util/HasLens.hs, educator/src/Dscp/Educator/Launcher/Mode.hs, educator/src/Dscp/Educator/Launcher/Resource.hs, witness/package.yaml, witness/src/Dscp/Witness/Launcher/Mode.hs, witness/src/Dscp/Witness/Launcher/Params.hs, witness/src/Dscp/Witness/Launcher/Resource.hs, witness/src/Dscp/Witness/Launcher/Runner.hs
Add functions to automatically traverse fields of a datatype and add `HasLens` instances.
Probably I will move all TH code to lootbox once you tell whether the approach is sensible.
=> [DSCP-255] Produce `instance HasLens` boilerplate with TH

witness/src/Dscp/Snowdrop/Expanders.hs
=> Remove warnings

.buildkite/pipeline.yml, README.md, docs/code-style.md, docs/pull_request_template.md
Remove trailing whitespace in all files.
Also,
=> Remove trailing whitespace

config.yaml
New deployment uses newly generated committee secret and also address structure has been changed, so config should be updated.
https://issues.serokell.io/SRK-8
Also,
=> Update alpha net config

faucet/src/Dscp/Faucet/Web/Logic.hs
Fix faucet to make it work in presense of fees.
This logic should covered by tests in separate commit/PR.
https://issues.serokell.io/DSCP-
Also,
=> [DSCP-304] Introduce fees to faucet

educator/database/schema.sql, educator/src/Dscp/DB/SQLite/Functions.hs, educator/src/Dscp/DB/SQLite/Instances.hs, educator/src/Dscp/DB/SQLite/Queries.hs, educator/src/Dscp/Educator/Web/Bot/Setting.hs, educator/src/Dscp/Educator/Web/Educator/API.hs, educator/src/Dscp/Educator/Web/Educator/Handlers.hs, educator/src/Dscp/Educator/Web/Educator/Types.hs, educator/tests/Test/Dscp/DB/SQLite/Queries.hs, educator/tests/Test/Dscp/Educator/Web/Educator/Queries.hs, educator/tests/Test/Dscp/Educator/Web/Instances.hs, educator/tests/Test/Dscp/Educator/Web/Student/Queries.hs, specs/disciplina/educator/api/educator.yaml
Please review it on per-commit basis.
https://issues.serokell.io/issue/DSCP-287
https://issues.serokell.io/issue/DSCP-288
Also,
=> [DSCP-287][DSCP-288] Educator API fixes

config.yaml
New entry necessary for educator node to be part of the witness
committee.
Add fifth entry to committee and bump distribution
https://issues.serokell.io/issue/OPS-583
Also,
=> Add 5th entry to committee

wallet/exec/Glue.hs, wallet/src/Dscp/Wallet/Backend.hs, wallet/src/Dscp/Wallet/Face.hs
Backend can now send log events to UI.
Exceptions are sent to UI automatically.
https://issues.serokell.io/DSCP-296
Also,
=> [DSCP-296] Show backend request logs in wallet Logs panel

config.yaml, core/src/Dscp/Core/Foundation/Coin.hs, core/src/Dscp/Core/Foundation/Educator.hs, core/src/Dscp/Core/Foundation/Instances.hs, core/src/Dscp/Core/Foundation/Witness.hs, core/src/Dscp/Util.hs, core/src/Dscp/Util/Timing.hs, docs/config-full-sample.yaml, educator/src/Dscp/DB/SQLite/Queries.hs, educator/src/Dscp/Educator/CLI.hs, educator/src/Dscp/Educator/Config.hs, educator/src/Dscp/Educator/Launcher/Entry.hs, educator/src/Dscp/Educator/Web/Bot/Setting.hs, educator/src/Dscp/Educator/Web/Student/Types.hs, educator/src/Dscp/Educator/Workers.hs, educator/tests/Test/Dscp/DB/SQLite/Queries.hs, educator/tests/Test/Dscp/Educator/Web/Educator/Queries.hs, run/educator.key, scripts/launch/node.sh, scripts/test/student-submissions-spam.sh, tools/README.md, tools/src/keygen/KeygenCommands.hs, witness/src/Dscp/CommonCLI.hs, witness/src/Dscp/Snowdrop/Types.hs, witness/src/Dscp/Web/Metrics.hs, witness/src/Dscp/Witness/Launcher/Entry.hs, witness/src/Dscp/Witness/Listeners/Listener.hs, witness/src/Dscp/Witness/Workers/Worker.hs
Make educator create and publish private blocks periodically.
https://issues.serokell.io/DSCP-298
Also,
=> [DSCP-298] Implement private block publishing worker

witness/src/Dscp/Witness/CLI.hs
Originally that field was optional, altering kind of committee used (open vs closed) depending
on whether the option was present or not.
In recent PR the CLI parser was modified so that it always expects
committee secret, and says there is no committee if committee failed to parse (i.e.
it was empty).
This fix makes committee secret truly optional, error is raised if
empty committee secret was passed. Note that this does not make CLI parser
override config by default because still there is the mandatory `comm-n` parameter.
https://issues.serokell.io/issue/DSCP-
- …
=> [DSCP-314] Fix CLI parser of `CommitteeSecret`

docs/pull_request_template.md
https://issues.serokell.io/issue/DSCP-
=> Fix links in the PR template

pkgs.nix, stack.yaml
They finally released a new version, which includes segfault fix.
Also, stack doesn't complain about missing files in serialise anymore.
=> Use cborg-0.2.1.0

educator/src/Dscp/Educator/Web/Bot/Handlers.hs, educator/src/Dscp/Educator/Web/Educator/API.hs, educator/src/Dscp/Educator/Web/Educator/Handlers.hs, educator/src/Dscp/Educator/Web/Educator/Queries.hs, educator/src/Dscp/Educator/Web/Educator/Types.hs, educator/src/Dscp/Educator/Web/Student/API.hs, educator/src/Dscp/Educator/Web/Student/Handlers.hs, educator/src/Dscp/Educator/Web/Student/Types.hs, educator/src/Dscp/Educator/Web/Types.hs, educator/tests/Test/Dscp/Educator/Bot/Endpoints.hs, educator/tests/Test/Dscp/Educator/Web/Educator/Queries.hs, specs/disciplina/educator/api/educator.yaml, specs/disciplina/educator/api/student.yaml
Best reviewed commit-by-commit.
https://issues.serokell.io/issue/DSCP-264
=> [DSCP-264] Improvements in Educator API, step 2

README.md
=> Add buildkite badge

witness/src/Dscp/Snowdrop/Expanders.hs, witness/src/Dscp/Snowdrop/PublicationValidation.hs, witness/src/Dscp/Snowdrop/Types.hs, witness/tests/Test/Dscp/Witness/Mode.hs, witness/tests/Test/Dscp/Witness/Tx/PublicationTxSpec.hs
See ticket below for the issue details.
I fixed by moving fee validation to expander.
https://issues.serokell.io/issue/DSCP-353
=> [DSCP-353] Fix publication when author = issuing witness

shell-native.nix, stack.yaml, witness/src/Dscp/Resource/Network.hs, witness/src/Dscp/Witness/CLI.hs
Uses new version of loot-network. See https://github.com/serokell/lootbox/pull/33. It is WIP only because we're waiting for the lootbox PR to be merged.
https://issues.serokell.io/issue/DSCP-281
=> [DSCP-281] [LTB-46] Use new loot-network version

educator/src/Dscp/Educator/CLI.hs, multi-educator/README.md, multi-educator/exec/Main.hs, multi-educator/package.yaml, multi-educator/src/Dscp/MultiEducator.hs, multi-educator/src/Dscp/MultiEducator/CLI.hs, multi-educator/src/Dscp/MultiEducator/Config.hs, multi-educator/src/Dscp/MultiEducator/Launcher.hs, multi-educator/src/Dscp/MultiEducator/Launcher/Entry.hs, multi-educator/src/Dscp/MultiEducator/Launcher/Mode.hs, multi-educator/src/Dscp/MultiEducator/Launcher/Params.hs, multi-educator/src/Dscp/MultiEducator/Launcher/Resource.hs, multi-educator/src/Dscp/MultiEducator/Launcher/Runner.hs, multi-educator/src/Dscp/MultiEducator/Web/Educator.hs, multi-educator/src/Dscp/MultiEducator/Web/Educator/API.hs, multi-educator/src/Dscp/MultiEducator/Web/Educator/Auth.hs, multi-educator/src/Dscp/MultiEducator/Web/Educator/Handlers.hs, multi-educator/src/Dscp/MultiEducator/Web/Educator/Logic.hs, multi-educator/src/Dscp/MultiEducator/Web/Educator/Types.hs, multi-educator/src/Dscp/MultiEducator/Web/Server.hs, scripts/launch/node.sh, stack.yaml
https://issues.serokell.io/issue/DSCP-283
=> [DSCP-283] Centralized Educator

stack.yaml
https://issues.serokell.io/issue/DSCP-
=> [DSCP-281] Update loot-networking with wrong tag fix

core/src/Dscp/Core/Slotting.hs, core/src/Dscp/Util/Time.hs, educator/tests/Test/Dscp/Educator/Mode.hs, witness/src/Dscp/Witness/Launcher/Context.hs, witness/src/Dscp/Witness/Launcher/Runner.hs, witness/src/Dscp/Witness/TestConfig.hs, witness/tests/Test/Dscp/Witness/Block/BlockSpec.hs, witness/tests/Test/Dscp/Witness/Explorer/ExplorerSpec.hs, witness/tests/Test/Dscp/Witness/Mode.hs
For the sake of #328 get passing tests in presence of slot verification I had to mock slotting.
However, mocking the time entirely occurred to be even simpler in some sense.
https://issues.serokell.io/issue/DSCP-390
=> [DSCP-390] Mock time

core/src/Dscp/Util/Test.hs, educator/src/Dscp/DB/SQLite/Functions.hs, educator/src/Dscp/DB/SQLite/Util.hs, educator/src/Dscp/Educator/DB/DSL/Interpret/Sqlite3.hs, educator/src/Dscp/Educator/DB/Instances.hs, educator/src/Dscp/Educator/DB/Queries.hs, educator/src/Dscp/Educator/Logic/Publishing.hs, educator/src/Dscp/Educator/Web/Bot/Setting.hs, educator/src/Dscp/Educator/Web/Educator/Handlers.hs, educator/src/Dscp/Educator/Web/Educator/Queries.hs, educator/src/Dscp/Educator/Web/Logic.hs, educator/src/Dscp/Educator/Web/Queries.hs, educator/src/Dscp/Educator/Web/Server.hs, educator/src/Dscp/Educator/Web/Student/Queries.hs, educator/src/Dscp/Educator/Web/Types.hs, educator/tests/Test/Dscp/DB/SQLite/Queries.hs, educator/tests/Test/Dscp/DB/SQLite/Real/Transactions.hs, educator/tests/Test/Dscp/Educator/Mode.hs, educator/tests/Test/Dscp/Educator/Web/Educator/Queries.hs, educator/tests/Test/Dscp/Educator/Web/Scenarios.hs, educator/tests/Test/Dscp/Educator/Web/Student/Queries.hs
Use directly a monad which is instance of `MonadBeam`.
This allows us not to implement `MonadBeam` with undefined methods, not without
plenty of other workarounds though.
https://issues.serokell.io/issue/DSCP-406
=> [DSCP-406] Remove DBT

witness/src/Dscp/Witness/Web/Server.hs
FairCV checking API uses `PUT` method, need to add it to CORS.
We should enforce CORS coherence with API in DSCP-419.
=> [SRK-8] Add `PUT` method to witness API's CORS

educator/README.md
=> Fix typo in doc

core/src/Dscp/Util/Test.hs, hpack/definitions.yaml, witness/src/Dscp/Witness/Logic/Getters.hs, witness/tests/Test/Dscp/Witness/Common.hs, witness/tests/Test/Dscp/Witness/Explorer/Explorer.hs, witness/tests/Test/Dscp/Witness/Getters.hs
:man_shrugging: 
https://issues.serokell.io/issue/DSCP-460
=> [DSCP-460] Add tests on `getPublicationByHeaderHash`

pkgs.nix
Update nixpkgs for less divergence from upstream. Needed for consistency with disciplina-nixops.
https://issues.serokell.io/issue/OPS-623
=> [OPS-623] update nixpkgs

pdfs/README.md, pdfs/app/Main.hs, pdfs/package.yaml, pdfs/src/Pdf/Scanner.hs, pdfs/tests/Main.hs, specs/disciplina/witness/api/witness.yaml, stack.yaml, witness/package.yaml, witness/src/Dscp/Witness/Web/API.hs, witness/src/Dscp/Witness/Web/Client/Logic.hs, witness/src/Dscp/Witness/Web/Handlers.hs, witness/src/Dscp/Witness/Web/Logic.hs, witness/src/Dscp/Witness/Web/Types.hs
https://issues.serokell.io/issue/DSCP-438
=> [DSCP-438] Checkcv-PDF endpoint

core/src/Dscp/Resource/Class.hs, core/src/Dscp/Util/TimeLimit.hs
This is the first part of the mentioned ticket where I'm trying to make our application
tolerant to freeze of its components.
In particular, all resources cleanup is now limited in time.
On timeout we print an error, and abandon that cleanup sending an exception to it.
**Why this relates to DSCP-468.**
How actually happens the bug with the node freezing on Postgres authentication failure:
* Networking resources are allocated;
* Attempt to allocate SQL resources is performed, including connections to the database
and schema preparation (and all these using `componentm` library);
* Allocation fails (in particular, connection to the database fails) and error is properly
thrown. Nothing is printed yet, because `componentm` tries to destroy all already
allocated resources before printing full …
=> [DSCP-468] Set timeout on resources teardown

educator/README.md
=> [SRK-8] Make educator README testing section more concise

stack.yaml
It contains the fix against networking resources release freezing.
https://issues.serokell.io/issue/DSCP-457
=> [DSCP-457] Bump version of lootbox with fixed networking

scripts/launch/node.sh
Now this does not always look pretty (because of bash limitations), but you always
see what is going wrong when it is.
https://issues.serokell.io/issue/DSCP-405
=> [DSCP-405] Do not hide database errors in scripts

stack.yaml
=> [SRK-8] Set servant-util dependency on commit from `master`

core/src/Dscp/Crypto/Util.hs, default.nix, educator/src/Dscp/Educator/Web/Educator/Error.hs, educator/src/Dscp/Educator/Web/Student/Error.hs, pdfs/package.yaml, pdfs/src/Pdf/FromLatex.hs, scripts/test/client-api-ghci.sh, stack.yaml, tools/src/faircv/Main.hs, tools/src/keygen/KeygenSecret.hs
Some fixes required for DSCP-475 which are not an immediate part of logic. 
**Review on per-commit basis is highly recommended.**
https://issues.serokell.io/issue/DSCP-475
=> [DSCP-475] Cert logic preparations

core/src/Dscp/Util/Exceptions.hs, default.nix, docs/config-full-sample.yaml, educator/src/Dscp/Educator/Config.hs, educator/src/Dscp/Educator/Launcher/Mode.hs, educator/src/Dscp/Educator/Launcher/Resource.hs, educator/src/Dscp/Educator/Web/Educator/Queries.hs, educator/src/Dscp/Educator/Web/Types.hs, educator/tests/Test/Dscp/Educator/Certificates.hs, educator/tests/Test/Dscp/Educator/Mode.hs, multi-educator/src/Dscp/MultiEducator/Config.hs, multi-educator/src/Dscp/MultiEducator/Launcher/Mode.hs, multi-educator/src/Dscp/MultiEducator/Launcher/Resource.hs, pdfs/package.yaml, pdfs/src/Pdf/FromLatex.hs, pdfs/test-pdf/Main.hs, pkgs.nix, release.nix, shell-native.nix
Missed that when reviewed @Martoon-00 's pr on DSCP-475 :angry: 
Also includes a bunch of changes, mostly to `nix` files, which allow for deployment of `xelatex` with all necessary modules as well.
https://issues.serokell.io/issue/DSCP-475
=> [DSCP-475] Update sample config and set up `xelatex` for deployment.

core/src/Dscp/Core/Arbitrary.hs, multi-educator/src/Dscp/MultiEducator/Launcher/Mode.hs, multi-educator/src/Dscp/MultiEducator/Launcher/Resource.hs, multi-educator/src/Dscp/MultiEducator/Web/Educator/Auth.hs, scripts/launch/node.sh, stack.yaml, witness/src/Dscp/Network/Wrapped.hs
A pack of crucial bugfixes.
**Review on per-commit basis is recommended.**
https://issues.serokell.io/issue/DSCP-496
=> [DSCP-496] Workers in multi-educator bug
