disciplina.cabal, src/educator/EducatorParams.hs, src/educator/Main.hs, src/witness/Main.hs, src/witness/WitnessParams.hs
Having plain 'Params' modules is really something pleasant, but
unfortunately duplications break ghci and deliver inconviniencies into work
with intero, so I'm for having unique module names in favor of faster builds.
=> Rename `Params.hs` modules to get unique names

disciplina.cabal, log-config.yaml, src/Dscp/CLI/Common.hs, src/Dscp/Educator/Launcher/Mode.hs, src/Dscp/Educator/Launcher/Runner.hs, src/Dscp/Launcher/Mode.hs, src/Dscp/Launcher/Params.hs, src/Dscp/Launcher/Resource.hs, src/Dscp/Listeners/Listener.hs, src/Dscp/Transport/TCP.hs, src/Dscp/Witness/Internal.hs, src/Dscp/Witness/Launcher/Mode.hs, src/Dscp/Witness/Launcher/Resource.hs, src/Dscp/Witness/Launcher/Runner.hs, src/Dscp/Workers/Worker.hs, src/educator/Main.hs, src/witness/Main.hs, stack.yaml, tools/disciplina-tools.cabal, tools/src/simulacrum/Main.hs
This switches logging to one based on lootbox.
There were several technical decisions taken:
* Using `RIO` newtype instead of `ReaderT ctx IO`. Simply speaking, it is done because `MonadLogging` typeclass provided by lootbox is already instantiated with `instance (r ~ Capabilities) => MonadLogging (ReaderT r IO)`, and I wanted to avoid defining overlapping instances.
* Logs of educators and witnesses are assumed to go into different folders (`logs/educator` and `logs/witness` accordingly) via passing `--log-dif` cmd line parameter, so educators and witnesses can share the same config without printing to the same file. (perhaps the time has come to write a simple launcher script).
Also see https://github.com/serokell/lootbox/pull/15.
Can not be merged until:
=> [DSCP-104] Loot log

package.yaml, src/Dscp/CLI/Common.hs, src/Dscp/DB.hs, src/Dscp/DB/Real.hs, src/Dscp/DB/Rocks.hs, src/Dscp/DB/Rocks/Class.hs, src/Dscp/DB/Rocks/Real.hs, src/Dscp/DB/Rocks/Real/Functions.hs, src/Dscp/DB/Rocks/Real/Types.hs, src/Dscp/DB/SQLite.hs, src/Dscp/DB/SQLite/Class.hs, src/Dscp/DB/SQLite/Error.hs, src/Dscp/DB/SQLite/Functions.hs, src/Dscp/DB/SQLite/Types.hs, src/Dscp/Educator/Launcher/Mode.hs, src/Dscp/Educator/Launcher/Params.hs, src/Dscp/Educator/Launcher/Resource.hs, src/Dscp/Educator/Launcher/Runner.hs, src/Dscp/Launcher/Mode.hs, src/Dscp/Launcher/Resource.hs, src/Dscp/Launcher/Rio.hs, src/Dscp/Transport/TCP.hs, src/Dscp/Util.hs, src/Dscp/Witness/Launcher/Mode.hs, src/Dscp/Witness/Launcher/Params.hs, src/Dscp/Witness/Launcher/Resource.hs, src/Dscp/Witness/Launcher/Runner.hs, src/educator/EducatorParams.hs, src/educator/Main.hs, src/witness/Main.hs
Within this PR we do:
* add access to SQL DB operations into context to educator
* along with adding dedicated typeclasses into workmode
* allowing both real and in-memory work in theory (thus no separated `SQLite/Real/*` modules)
* rename `DB` -> `RocksDB` for existing types/functions, move modules in `DB` into `Rocks` subfolder
=> [DSCP-102] Provide SQLite context

package.yaml, src/Dscp/Educator/Launcher/Runner.hs, src/Dscp/Resource/Class.hs, src/Dscp/Witness/Launcher/Runner.hs
By default exceptions on resource allocation are just rethrown and printed by ghc using 'Show' instance. In this PR exceptions are handled and printed nicely.
Before:
``
disciplina-educator: ComponentBuildFailed {componentErrorBuildErrors = [ComponentAllocationFailed "Educator secret key storage" /home/elena/.local/share/disciplina/secret.key: openBinaryFile: does not exist (No such file or directory)], componentErrorTeardownResult = BranchResult {resultDescription = "Educator (real mode)", resultElapsedTime = 0.000652s, resultDidFail = False, resultListing = [EmptyResult {resultDescription = "Educator secret key storage"},LeafResult {resultDescription = "SQLite DB", resultElapsedTime = 0.000108s, resultError = Nothing},LeafResult {resultDescription = "netcli", resultElapsedTime = …
=> [DSCP-127] Pretty errors on application failure

src/Dscp/DB/SQLite/Functions.hs, src/Dscp/DB/SQLite/Schema.hs, src/Dscp/Educator/Launcher/Runner.hs, src/Dscp/Educator/Secret/Real/Error.hs, src/Dscp/Educator/Secret/Real/Functions.hs, src/Dscp/Resource/AppDir.hs, src/Dscp/Resource/Class.hs, src/Dscp/Resource/Functions.hs, src/Dscp/Resource/Logging.hs, src/Dscp/Resource/Network.hs, src/Dscp/Resource/Other.hs, src/Dscp/System/FileMode.hs, src/Dscp/Witness/Launcher/Resource.hs, src/Dscp/Witness/Launcher/Runner.hs
Split resource allocation into two phases, first prepares logging so that in second phase we can use it for other resources allocation and reporting possible errors.
=> [DSCP-124] Provide logging context into resource allocation

.gitignore, .stylish-haskell.yaml, hpack/definitions.yaml, package.yaml, src/Dscp/Core/ATG.hs, src/Dscp/Core/Serialise.hs, src/Dscp/Core/Types.hs, src/Dscp/DB/DSL/Class.hs, src/Dscp/DB/DSL/Interpret/IO.hs, src/Dscp/DB/DSL/Interpret/SimpleTxDB.hs, src/Dscp/DB/DSL/Interpret/Sqlite3.hs, src/Dscp/DB/SQLite/Class.hs, src/Dscp/DB/SQLite/Functions.hs, src/Dscp/DB/SQLite/Instances.hs, src/Dscp/DB/SQLite/Queries.hs, src/Dscp/Educator/Txs.hs, src/Dscp/Util.hs, tests/Test/Common.hs, tests/Test/Dscp/Core/ATG.hs, tests/Test/Dscp/DB/DSL/Interpret/SimpleTxDB.hs, tests/Test/Dscp/DB/SQLite/Common.hs, tests/Test/Dscp/DB/SQLite/Instances.hs, tests/Test/Dscp/DB/SQLite/Queries.hs, tests/Test/Dscp/Educator/BlockValidation.hs
Has to make tests run in non-parallel mode until I implement database changer.
Implemented all questions from `[DSCP-112]`, but only tested `submitAssignment` yet.
All other functions are to create actual entities so I can test the question answerers.
=> [DSCP-114] [WIP] SQL queries for fetching necessary data for student

lib/src/Dscp/Core/Types.hs, lib/src/Dscp/Snowdrop/AccountValidation.hs, lib/src/Dscp/Snowdrop/Configuration.hs, lib/src/Dscp/Snowdrop/Expanders.hs, lib/src/Dscp/Snowdrop/Validators.hs
- Changed `HasPrism` to `HasGetter` for all the validator properties because we don't need to reconstruct `proof` from anything. I blindly copied `HasPrism` constraints back then. Thats what reading SD code does to people.
- Implemented all validatior requirements on `Proofs`.
- Changed requirements to `Expander` to signed `(TxId, PublicKey)`, since `Address` is wrapper around `Hash PublicKey` and `AuthorId` can be retrieved from that.
- Pulled authentication in validator into separate method.
=> [DSCP-159] Integrated validators and changed them a bit

wallet/package.yaml, wallet/src/Dscp/Wallet/Knit.hs
Coin parsing no longer interfers with number parsing.
Both number literals and `get-balance` return values can be used as input to `tx-out`.
Still, numbers are properly validated on input.
=> [AD-311] Remove Coin token, make tyCoin accept both ValueCoin and ValueNumber

wallet/README.md, wallet/src/Dscp/Wallet/Knit.hs
Parsing bare unquoted strings without strictly defined length as public/secret key broke some other Knit commands.
Thus, we require quotes around keys now.
Also, secret keys are always encrypted now. Empty passphrase is used if no passphrase is supplied.
=> [AD-310] Handle keys as strings in Knit

default.nix
Output an attrset with all the relevant packages.
I could've sworn `getAttrs` exists in nixpkgs already, but couldn't find it.
=> [OPS-330] [OPS-331] refactor nix to output multiple packages

stack.yaml
LTS has cryptonite-openssl-0.6, which causes the following build error:
```
<command line>: can't load .so/.DLL for: /home/goodsoft/.stack/snapshots/x86_64-linux-tinfo6/lts-11.17/8.2.2/lib/x86_64-linux-ghc-8.2.2/libHScryptonite-openssl-0.6-8ex6yYmKYbJFQoAbbvgmKg-ghc8.2.2.so (/home/goodsoft/.stack/snapshots/x86_64-linux-tinfo6/lts-11.17/8.2.2/lib/x86_64-linux-ghc-8.2.2/libHScryptonite-openssl-0.6-8ex6yYmKYbJFQoAbbvgmKg-ghc8.2.2.so: undefined symbol: EVP_CIPHER_CTX_init)
```
See also https://serokell.slack.com/archives/C9B1DAMDJ/p1532533676000094
=> Bump cryptonite-openssl version to 0.7

core/src/Dscp/Core/Arbitrary.hs, core/src/Dscp/Core/Foundation/Educator.hs, core/src/Dscp/Util/Test.hs, educator/database/schema.sql, educator/src/Dscp/DB/DSL/Interpret/SimpleTxDB.hs, educator/src/Dscp/DB/DSL/Interpret/Sqlite3.hs, educator/src/Dscp/DB/SQLite/Instances.hs, educator/src/Dscp/DB/SQLite/Queries.hs, educator/src/Dscp/DB/SQLite/Types.hs, educator/src/Dscp/Educator/Arbitrary.hs, educator/src/Dscp/Educator/Web/Student/Logic.hs, educator/src/Dscp/Educator/Web/Student/Queries.hs, educator/src/Dscp/Educator/Web/Student/Types.hs, educator/tests/Test/Dscp/DB/DSL/Interpret/SimpleTxDB.hs, educator/tests/Test/Dscp/DB/SQLite/Common.hs, educator/tests/Test/Dscp/DB/SQLite/Queries.hs, educator/tests/Test/Dscp/Educator/Bot/Endpoints.hs, educator/tests/Test/Dscp/Educator/Common.hs, educator/tests/Test/Dscp/Educator/Web/Student/Queries.hs, specs/disciplina/educator/api/student.yaml
Actually this required completely another approach to testing, because now there is no large data like `SignedSubmission` which would keep all test case input.
So I artificially introduced datatype which would keep all possible data test case may require.
=> [DSCP-180] Keep just reference on `Assignment` in `Submission`

configuration.yaml, core/src/Dscp/Core/Aeson.hs
This would introduce new configuration format for _governance_ param in configuration.yaml file.
```
governance:
type: governanceOpen
OR
governance:
type: committeeOpen
secret: "secret"
n: N
OR
governance:
type: committeeClosed
participants: [p_1, 
p_2,
...
p_n]
```
=> [DSCP-167] Proper JSON instances for configuration types

educator/src/Dscp/Educator/Web/Server.hs, educator/src/Dscp/Educator/Web/Student/API.hs, educator/src/Dscp/Educator/Web/Student/Auth.hs, specs/disciplina/educator/api/student.yaml
This PR refactors Auth code by creating a custom `Auth'` API type that has its own `HasServer` instance that directly provides `Student` to the handler.
Initially this type was planned to be just a wrapper over `Auth` but as I later found out it's way easier and better to implement fully custom type and not use `Auth` all-together. 
Here's why:
* Unwrapping the type in `route` is not trivial.
* `HasServer` instance for `Auth` adds SetCookie headers with JWT with signed auth data. Not only we're not supposed to set such headers on the server, this leads to several other problems which I describe in other points below.
* Since `HasServer` for `Auth` sets cookie headers, it requires `CookieSettings` in the server context, so we have to provide it. It's not a big deal, but pollutes the …
=> [DSCP-141] Refactor Auth code

stack.yaml, wallet/app-vty/Glue.hs
Now you can name an account in any way you want and still be able to copy-paste its address.
=> [AD-269] Show account address as a wallet ID

scripts/launch/demo.sh
For me `sh` does not know what is `set -o pipefail`
=> Set bash in shebang of demo launcher

witness/src/Dscp/Witness/Mempool/Logic.hs, witness/src/Dscp/Witness/Workers/Worker.hs
- Also `failedTxs` `TVar` is now filled with txs.
- But is never cleaned.
=> [DSCP-208] Prevented application/validation exns from leaking out

faucet/src/Dscp/Faucet/CLI.hs, faucet/src/Dscp/Faucet/Launcher/Params.hs, wallet/README.md, wallet/exec-cli/Main.hs, wallet/exec/Main.hs, wallet/package.yaml, wallet/src/Dscp/Wallet/Backend.hs, wallet/src/Dscp/Wallet/CLI.hs, witness/package.yaml, witness/src/Dscp/CommonCLI.hs, witness/src/Dscp/Web/Server.hs, witness/src/Dscp/Witness/Web/Client/Logic.hs
Using `Servant.Client.BaseUrl` instead of `NetworkAddress` for flexible URL parsing.
Also, using `http-client-tls` instead of `http-client` for SSL/TLS support.
`--wallet-server` is renamed to `--witness` for less typing.
Both wallet and faucet can now connect to witness using hostname or even full-fledged URL.
Example: `dscp-wallet --witness witness-1.disciplina.serokell.team`
HTTP is used by default if no protocol is provided (didn't bother monkey-patching `servant-client`), but it should be fine, as the requests will be redirected to HTTPS by nginx anyway.
Next step would be making `--witness` parameter optional for the wallet and hard-coding some sensible default list of witness nodes.
=> [DSCP-221] Support HTTPS in witness client

educator/src/Dscp/Educator/Web/Bot/Handlers.hs, educator/src/Dscp/Educator/Web/Bot/Setting.hs
Since student cannot send more than one submission for the same assignment for now,
easter egg with providing advanced courses on 3 submissions for the same assignment
didn't work. But not anymore.
=> [SRK-8] Fix advanced courses in bot

witness/src/Dscp/Snowdrop/Expanders.hs
Without this fix, attempt to spend money from new account without money reports `Internal error: Source account is not registered in chain`
=> [DSCP-209] Fix error message on attempt to spend money from new account

witness/src/Dscp/Witness/Logic/Traversals.hs
When we list transactions starting from a particular transaction in the middle of a block,
we have to drop transactions which happened _after_ specified one, which we didn't.
=> [DSCP-232] Fix transaction paging in BE API

wallet/exec-cli/Main.hs, wallet/exec/Main.hs, wallet/package.yaml, wallet/src/Dscp/Wallet/CLI.hs
Example:
`dscp-wallet-cli --witness <witness> --knit "get-balance <address>"`
=> [DSCP-231] Allow specifying a knit command as dscp-wallet-cli argument

stack.yaml, witness/src/Dscp/Snowdrop/Actions.hs, witness/src/Dscp/Snowdrop/Configuration.hs, witness/src/Dscp/Witness/Logic/Processing.hs, witness/src/Dscp/Witness/Mempool/Logic.hs, witness/src/Dscp/Witness/Mempool/Type.hs
1. Fixes an issue related to nonces, mentioned in ticket https://issues.serokell.io/issue/DSCP-241 as error #3, which could be deterministically reproduced when creating transactions with same destination address within a single slot. Original issue yet remains.
Fix is in snowdrop, related commit: https://github.com/serokell/blockchain-util/commit/0252789e6b3d562fd189cbc66e4bfa76d363138f.
Approved by @pva701.
2. Fixes problem with `TxOf`s mentioned in issue as well, by making mempool consider block storage.
=> [DSCP-241] Fix one block application issue

stack.yaml
See the relevant commit in the loot-network for the details:
https://github.com/serokell/lootbox/commit/34e389808e34f1cfa56f456773682325bed56d17
=> [DSCP-246] Update loot-network with empty peers zero division bug fixed

core/src/Dscp/Core/Arbitrary.hs, educator/tests/Test/Dscp/DB/SQLite/Queries.hs, educator/tests/Test/Dscp/Educator/Web/Educator/Queries.hs, educator/tests/Test/Dscp/Educator/Web/Student/Queries.hs
Previously I introduced generation of whole test environments which would
produce interconnected courses, assignments, submissions e.t.c.
One of invariants is one can zip produced list of courses/submissions/whatever
and get a list of tuples containing entities corresponding to each other.
Although I did a mistake while satisfying that invariant.
Now I reworked generation a bit a made it more concise.
100 runs of tests passed ok.
=> [DSCP-176] Fix tests

default.nix
This uses a whitelist/blacklist approach along with builtins.path, to remove any dependency on the source folder name and documentation or nix files.
=> default.nix: attempt less rebuilds

release.nix
If wallet config is there to stay, it should be included in the release wrapper.
=> Add alpha config to disciplina-wallet-wrapped

core/src/Dscp/Core/Foundation/Instances.hs
Automatically generated instance is not even valid if I check with
`validFlatTerm`.
Now it follows the tutorial on CBOR.
Testing:
* Sanity of new representation is tested in ghci
* `deserialise (serialise sub) === sub` is tested manually in ghci
=> [DSCP-263] Provide manual `instance Serialise Submission`

config-full-sample.yaml, config.yaml, core/src/Dscp/Core/Aeson.hs, core/src/Dscp/Core/Config.hs, core/src/Dscp/Core/Fees.hs, core/src/Dscp/Util.hs, wallet/src/Dscp/Wallet/Backend.hs, witness/src/Dscp/Snowdrop/Expanders.hs, witness/tests/Test/Dscp/Witness/FeeSpec.hs, witness/tests/Test/Dscp/Witness/Mode.hs, witness/tests/Test/Dscp/Witness/Tx/MoneyTxSpec.hs, witness/tests/Test/Dscp/Witness/Tx/PublicationTxSpec.hs
Allow not only linear policies.
Since we have several kinds of transactions, I used GADTs to make it possible to apply some policies only to specific kind of transactions, maybe I overengeneered.
todo:
=> [DSCP-252] Generalised fee policy

README.md, shell-native.nix, stack.yaml
> If you are on a single-user Nix install (`nix-shell -p nix-info --run nix-info`
should say `multi-user?: no`), omit `sudo` in the command above.
=> Add a build note for single-user installs

.stylish-haskell.yaml, config-full-sample.yaml, educator/src/Dscp/Educator/CLI.hs, educator/src/Dscp/Educator/Web/Auth.hs, educator/src/Dscp/Educator/Web/Educator/API.hs, educator/src/Dscp/Educator/Web/Educator/Auth.hs, educator/src/Dscp/Educator/Web/Params.hs, educator/src/Dscp/Educator/Web/Server.hs, educator/src/Dscp/Educator/Web/Student/API.hs, educator/src/Dscp/Educator/Web/Student/Auth.hs, scripts/launch/node.sh, witness/src/Dscp/CommonCLI.hs
In order to avoid keeping two API types - with and without authentication - I pass that option via context along with educator secret key.
=> [DSCP-275] [DSCP-282] Make Educator and Student APIs authentication optional

docs/api-types.md, hpack/definitions.yaml
The format of `Address` serialization changed, need to catch up.
Result: https://github.com/DisciplinaOU/disciplina/blob/martoon%2Fdscp271-complete-api-doc/docs/api-types.md#L22
Also, I'm starting to promote `httpie` as it was discussed with John, since it is easy to install, requires less boilerplate and provides a much more detailed output on what's going on.
=> [DSCP-271] Complete API doc

.buildkite/pipeline.yml
Changed buildkite build order, so release builds run after disciplina build, and only if it passes.
=> buildkite: wait for succesful build before compiling release

stack.yaml
If someone wants to build with Nix, they can either set it in their user conf, pass `--nix` flag to Stack or just enter `nix-shell`.
=> Remove nix: enable: true

.buildkite/pipeline.yml, README.md, release.nix
Current recommendation is not as good as it requires downloading way more stuff from cache and causes path conflict when installed to user environment.
https://issues.serokell.io/OPS-538
Also,
=> Recommend `nix-env -f release.nix -iA disciplina-static` to frontend devs

faucet/src/Dscp/Faucet/Config.hs
Seems like Haddock does not support documenting individual type entries,
so it was failing to build. After a little Googling on Haddock markup,
this seems like the next best way to handle it.
Also,
=> Fix Haddock complaints in Faucet/Config.hs

tools/README.md, tools/package.yaml, tools/src/keygen/KeygenSecret.hs, tools/src/keygen/Main.hs
The main mistake which was present - when one does `echo "something"` the newline
symbol is automatically inserted, and it cannot be parsed by e.g. `fromBase64`
obviously.
There was another mistake - I selected a bytestring parsing way (raw/hex/base64)
just depending on whether it was parsed successfully, disregard whether
we can later convert it to the required data.
Tested everything this time.
https://issues.serokell.io/DSCP-274
Also,
=> [DSCP-274] Fix keygen

witness/src/Dscp/Snowdrop/AccountValidation.hs, witness/src/Dscp/Snowdrop/Configuration.hs, witness/src/Dscp/Snowdrop/Expanders.hs, witness/tests/Test/Dscp/Witness/Tx/MoneyTxSpec.hs
Check that transaction has enough money remaining for fees.
Tested with wallet:
https://issues.serokell.io/DSCP-269
Also,
=> [DSCP-269] Add missing fees validation check

core/src/Dscp/Util/Test.hs, educator/tests/Test/Dscp/DB/SQLite/Common.hs, educator/tests/Test/Dscp/Educator/Bot/Endpoints.hs, educator/tests/Test/Dscp/Educator/Web/Educator/Queries.hs, educator/tests/Test/Dscp/Educator/Web/Student/Queries.hs, witness/tests/Test/Dscp/Witness/Block/BlockSpec.hs, witness/tests/Test/Dscp/Witness/Tx/FeeSpec.hs, witness/tests/Test/Dscp/Witness/Tx/PublicationTxSpec.hs
Decreases educators tests passing time by 2x-3x
https://issues.serokell.io/DSCP-290
Also,
=> [DSCP-290] Generate less data in educator tests.

core/src/Dscp/Core/Foundation/Educator.hs, educator/src/Dscp/Educator/Web/Auth.hs, educator/src/Dscp/Educator/Web/Educator/Types.hs, educator/src/Dscp/Educator/Web/Server.hs, educator/src/Dscp/Educator/Web/Student/Types.hs, educator/src/Dscp/Educator/Web/Types.hs, witness/src/Dscp/Util/Servant.hs
Requests to student & educator APIs are logged.
https://issues.serokell.io/DSCP-222
New buildable instances for educator's types.
serveWithContext accepts different proxy which allows logging API requests and responses.
Also,
=> [DSCP-222] Enable logging in educator APIs

educator/src/Dscp/DB/SQLite/Queries.hs, educator/src/Dscp/Educator/Web/Educator/API.hs, educator/src/Dscp/Educator/Web/Educator/Handlers.hs, educator/src/Dscp/Educator/Web/Educator/Queries.hs, educator/src/Dscp/Educator/Web/Logic.hs, educator/src/Dscp/Educator/Web/Queries.hs, educator/src/Dscp/Educator/Web/Student/Handlers.hs, educator/src/Dscp/Educator/Web/Student/Logic.hs, educator/tests/Test/Dscp/DB/SQLite/Queries.hs, educator/tests/Test/Dscp/Educator/Web/Educator/Queries.hs, educator/tests/Test/Dscp/Educator/Web/Student/Queries.hs, specs/disciplina/educator/api/educator.yaml
Changed multiple GET endpoints into optional query parameters.
TODO (some other time):
- fix ugly `fromJust` in `commonGetAssignments`
- bring some order and tidiness into API implementation
- run this code at least once
https://issues.serokell.io/issue/DSCP-307
=> [DSCP-307] Simplify Educator API, bring in line with spec

core/src/Dscp/System/FileMode.hs, witness/src/Dscp/Resource/Keys/Error.hs, witness/src/Dscp/Resource/Keys/Functions.hs
When reading a file we did not create immediately before, we can not be certain
to have the necessary permissions for `chmod`. For example, the file might have
been provisioned separately, and be owned by root. Instead, check if we believe
the file has permissions that are too loose and throw an error.
This PR does not include tests. Because I honestly have no idea how to
implement them.
https://issues.serokell.io/issue/DSCP-303
Stylistic …
=> [DSCP-303] Replace blind chmod with permission check in readStore

core/src/Dscp/Core/Aeson.hs, core/src/Dscp/Core/Governance.hs, tools/src/keygen/KeygenSecret.hs, witness/src/Dscp/Witness/CLI.hs, witness/tests/Test/Dscp/Witness/Mode.hs
Prohibit empty `CommitteeSecret`s (throw an error when trying to decode empty string)
Add smart constructor to CommitteeSecret
Change exports and imports
https://issues.serokell.io/issue/DSCP-314
=> [DSCP-314] Prohibit empty CommitteeSecrets

witness/src/Dscp/Resource/Keys/Error.hs, witness/src/Dscp/Resource/Keys/Functions.hs
It contains DecryptionError, which might not only mean wrong passphrase, but also malformed key (cc Kostya Ivanov)
https://issues.serokell.io/issue/DSCP-322
=> [DSCP-322]  Rename SecretWrongPassPhraseError and provide better message for it

core/src/Dscp/Resource/AppDir.hs, wallet/src/Dscp/Wallet/KeyStorage.hs
A fallback is needed in case the $HOME environment variable is not set
This update uses $PWD as such fallback.
In the very unlikely case that this is not set either, `.` is used.
Noticing that the original code about this was repeated in twice (and that both needed to be modified in the same way) they were merged in a single place.
https://issues.serokell.io/issue/DSCP-293
- [X My code complies with the [style …
=> [DSCP-293] use PWD as HOME fallback, make getDataDir use getOSAppDir

specs/disciplina/educator/api/educator.yaml, specs/disciplina/educator/api/student.yaml, specs/disciplina/faucet/api/faucet.yaml, specs/disciplina/witness/api/witness.yaml
OpenAPI 3.0.0 addresses some shortcomings of Swagger 2.0
and makes it easier to specify precise API workings.
This is one-to-one conversion of all existing API specs
using https://openapi-converter.herokuapp.com/ tool.
Somewhat related to https://issues.serokell.io/issue/DSCP-264
=> Convert API specs to OpenAPI 3.0.0

config.yaml, core/package.yaml, core/src/Dscp/Core/Aeson.hs, core/src/Dscp/Core/Foundation/Coin.hs, wallet/exec/Glue.hs, wallet/src/Dscp/Wallet/Knit.hs, witness/src/Dscp/Snowdrop/Types.hs
These commits make DSCP token correspond the ERC-20 standard. A representation of the data type changes to `E-6` format in Buildable and ToJson instances. Wallet's Knit parsing adjusts the changes. Since the commits coin amount value is a string in terms of witness-api and configuration. So the config yaml file is adjusted as well.
https://issues.serokell.io/issue/DSCP-310
=> [DSCP-310]  Make Coin a Fixed fraction value instead of an integral value

core/src/Dscp/Resource/Logging.hs, core/src/Dscp/Util/Test.hs, docs/config-full-sample.yaml, faucet/src/Dscp/Faucet/Config.hs, run/syslog-config.yaml, scripts/launch/node.sh, stack.yaml, witness/src/Dscp/CommonCLI.hs, witness/src/Dscp/Witness/Config.hs
This adds syslog backend for logging.
NOTE: it is labeled WIP because it relies on a [yet unmerged branch](https://github.com/serokell/lootbox/tree/pasqu4le/lbt42-syslog-backend-for-loot-log) of `loot-box` made for issue [LTB-42](https://issues.serokell.io/issue/LTB-42)
There is now a new configuration option: `log-type` that defaults to `Syslog` but can be set to `Warper`. A new logging configuration file, that mimics the still-present warper one as much as possible, has been added: `run/syslog-config.yaml`.
https://issues.serokell.io/issue/DSCP-345
- …
=> [DSCP-345] syslog backend for logging

stack.yaml
This PR solves the problem of scrambled text in stderr output by `loot-log`'s Syslogger, by using a fork of `hslogger` that does this is in a thread-safe way.
NOTE: there is a yet unmerged branch on `lootbox` for this as well, but this PR does not use it, nor does not need it.
https://issues.serokell.io/issue/DSCP-361
=> [DSCP-361] fix corrupted syslog output on stderr

core/src/Dscp/Util.hs, scripts/launch/node.sh, scripts/test/student-submissions-spam.sh, tools/README.md, tools/src/keygen/KeygenCommands.hs, tools/src/keygen/KeygenOptions.hs, tools/src/keygen/KeygenSecret.hs, tools/src/keygen/Main.hs
Improves keygen interface. Adds help messages for each command of the keygen.
For instance:
`dscp-keygen --seed --command "address:hex"` -> `dscp-keygen --seed address --hex`.
https://issues.serokell.io/issue/DSCP-351
=> [DSCP-351] improve keygen commands

educator/src/Dscp/Educator/Web/Types.hs, specs/disciplina/educator/api/educator.yaml
Previous way serialized them as objects instead of as booleans, which was indeed weird and
didn't correspond to the documentation.
=> [DSCP-374] Fix serialisation of Bool-isomorphic types in educator APIs

core/src/Dscp/Util/Test.hs, specs/disciplina/witness/api/witness.yaml, witness/src/Dscp/Snowdrop/AccountValidation.hs, witness/src/Dscp/Snowdrop/Configuration.hs, witness/src/Dscp/Snowdrop/Expanders.hs, witness/src/Dscp/Snowdrop/Instances.hs, witness/src/Dscp/Snowdrop/Mode.hs, witness/src/Dscp/Snowdrop/Storage/Types.hs, witness/src/Dscp/Snowdrop/Types.hs, witness/src/Dscp/Witness/Listeners/Listener.hs, witness/src/Dscp/Witness/Logic/Apply.hs, witness/src/Dscp/Witness/Logic/Exceptions.hs, witness/src/Dscp/Witness/Logic/Getters.hs, witness/src/Dscp/Witness/Logic/Traversals.hs, witness/src/Dscp/Witness/Mempool/Logic.hs, witness/src/Dscp/Witness/Web/Logic.hs, witness/src/Dscp/Witness/Workers/Worker.hs, witness/tests/Test/Dscp/Witness/Explorer/ExplorerSpec.hs, witness/tests/Test/Dscp/Witness/Tx/MoneyTxSpec.hs
Generalizes getters/traversals in witness logic so that they work both in chain-only and chain+mempool modes (depending on caller's needs) and make explorer endpoints (`/transactions`,  `/publications`, `/transactions/{id}`, `/hash/{hash}`) take mempool into consideration.
To make actions which can work in two mentioned modes I introduced a special monad wrapper `SdReadM`, through which one can say exact mode he wishes to launch the action in. Another way would be to use old `SdM_ chgacc` (`chgacc` varies depending on selected mode), but IMO this case occurred to be [ugly](https://github.com/DisciplinaOU/disciplina/commit/1ed5fcb0a2dfb8ea8b3f79c97b3f566c28e13dde) (I can elaborate more on this if needed).
https://issues.serokell.io/issue/DSCP-335
Hint: a perfect PR has all the checkmarks …
=> [DSCP-335] Make explorer take mempool into consideration

educator/src/Dscp/Educator/Workers.hs, witness/src/Dscp/Witness/Mempool/Logic.hs, witness/src/Dscp/Witness/Workers/Worker.hs, witness/tests/Test/Dscp/Witness/Explorer/ExplorerSpec.hs, witness/tests/Test/Dscp/Witness/Tx/MoneyTxSpec.hs, witness/tests/Test/Dscp/Witness/Tx/PublicationTxSpec.hs
This makes sense as soon as validation fits better for such check.
Actually, we already have this check both for money and publication transactions.
https://issues.serokell.io/issue/DSCP-369
=> [DSCP-369] Make `addTxToMempool` not check whether tx is present

core/src/Dscp/Core/Foundation/Educator.hs, educator/src/Dscp/DB/SQLite/Functions.hs, educator/src/Dscp/DB/SQLite/Queries.hs, educator/tests/Test/Dscp/Educator/BlockValidation.hs, educator/tests/Test/Dscp/Educator/Mode.hs, witness/src/Dscp/Resource/Keys/Functions.hs, witness/src/Dscp/Resource/Keys/Types.hs, witness/src/Dscp/Snowdrop/Expanders.hs, witness/src/Dscp/Snowdrop/PublicationValidation.hs, witness/src/Dscp/Witness/Launcher/Resource.hs, witness/src/Dscp/Witness/Logic/Getters.hs, witness/src/Dscp/Witness/Logic/Traversals.hs, witness/tests/Test/Dscp/Witness/Mode.hs, witness/tests/Test/Dscp/Witness/Tx/PublicationTxSpec.hs
Make genesis header depend on educator's address.
https://issues.serokell.io/issue/DSCP-285
=> [DSCP-285] Make genesis header hash depend on educator it relates to

config.yaml, core/package.yaml, core/src/Dscp/Resource/Logging.hs, core/src/Dscp/Util/Test.hs, stack.yaml, witness/src/Dscp/Util/Servant.hs, witness/src/Dscp/Web/Server.hs
This PR modifies logging to be based on `co-log`, this required the creation of a syslog backend for `co-log` (`co-log-sys`) and an updated version of `loot-log` and `snowdrop-util` that make use of it.
NOTE: this PR is labeled as a WIP because it depends a yet unmerged branch of `lootbox` and an updated branch of `blockchain-util`.
https://issues.serokell.io/issue/DSCP-370
=> [DSCP-370] use new loot-log (based on co-log) for logging

specs/disciplina/witness/api/witness.yaml, witness/src/Dscp/Snowdrop/Expanders.hs, witness/src/Dscp/Snowdrop/Instances.hs, witness/src/Dscp/Snowdrop/Types.hs
It's inconvenient, as soon as far not any type implements `Data` and thus can be put
in one of `AccountException` constructors. Also, names of constructors are not that
beautiful to include them into public API as is.
https://issues.serokell.io/issue/DSCP-389
=> [DSCP-389] Remove `instance Data AccountException`

witness/tests/Test/Dscp/Witness/Tx/PublicationTxSpec.hs
We have to forbid publications which have author `A`, but witness of 'B'.
I didn't find an explicit check for this, but everything seems to be alright anyway.
Inspired by [Fair CV pull request](https://github.com/DisciplinaOU/disciplina/pull/324/files#diff-58e0a46ccef9aebf2531991f62fdef86R274).
https://issues.serokell.io/issue/DSCP-402
=> [DSCP-402] Add a test case on publication tx

educator/src/Dscp/Educator/Web/Bot/Handlers.hs, educator/src/Dscp/Educator/Web/Bot/Setting.hs, educator/src/Dscp/Educator/Web/Educator/API.hs, educator/src/Dscp/Educator/Web/Educator/Handlers.hs, educator/src/Dscp/Educator/Web/Educator/Types.hs, educator/src/Dscp/Educator/Web/Logic.hs, educator/src/Dscp/Educator/Web/Types.hs, educator/tests/Test/Dscp/Educator/Bot/Endpoints.hs, multi-educator/src/Dscp/MultiEducator/Launcher/Mode.hs, specs/disciplina/educator/api/educator.yaml, witness/src/Dscp/Witness/Logic/Getters.hs, witness/src/Dscp/Witness/Web/Logic.hs, witness/src/Dscp/Witness/Web/Types.hs
Add a way to fetch educator's info directly via Educator API.
https://issues.serokell.io/issue/DSCP-301
=> [DSCP-301] Add endpoint showing educator status

core/src/Dscp/Core/Arbitrary.hs, core/src/Dscp/Core/Foundation/Witness.hs, core/src/Dscp/Util.hs, core/src/Dscp/Util/Test.hs, witness/src/Dscp/Snowdrop/BlockMetaValidation.hs, witness/src/Dscp/Snowdrop/Configuration.hs, witness/src/Dscp/Snowdrop/Expanders.hs, witness/src/Dscp/Snowdrop/Types.hs, witness/src/Dscp/Snowdrop/Validators.hs, witness/src/Dscp/Witness/Listeners/Listener.hs, witness/src/Dscp/Witness/Logic/Apply.hs, witness/src/Dscp/Witness/Logic/Creation.hs, witness/src/Dscp/Witness/Web/Error.hs, witness/src/Dscp/Witness/Workers/Worker.hs, witness/tests/Test/Dscp/Witness/Block/BlockSpec.hs, witness/tests/Test/Dscp/Witness/Common.hs, witness/tests/Test/Dscp/Witness/Explorer/ExplorerSpec.hs, witness/tests/Test/Dscp/Witness/Tx/PublicationTxSpec.hs
Adding missing checks required me to add one more type of transaction - block meta, which is responsible for block-level stuff expansion and validation. It is not a true transaction though, rather just a helper, so it is not signed, it does not appear in network messages and is not visible in explorer API.
https://issues.serokell.io/issue/DSCP-261
=> [DSCP-261] Validate block's slotId and difficulty

faucet/tests/Test/Dscp/Faucet/CLI.hs, witness/package.yaml, witness/tests/Main.hs, witness/tests/Spec.hs, witness/tests/Test/Dscp/Witness/Block/Block.hs, witness/tests/Test/Dscp/Witness/CLI.hs, witness/tests/Test/Dscp/Witness/Explorer/Explorer.hs, witness/tests/Test/Dscp/Witness/Serialise.hs, witness/tests/Test/Dscp/Witness/Tx/Fee.hs, witness/tests/Test/Dscp/Witness/Tx/MoneyTx.hs, witness/tests/Test/Dscp/Witness/Tx/PublicationTx.hs
Replace hspec discovery with tasty discovery. DSL for specs definitions is still hspec.
WIP: on every second launch I get `lost signal due to full pipe: 11` errors.
https://issues.serokell.io/issue/DSCP-372
=> [DSCP-372] Switch witness tests to tasty-discovery

educator/package.yaml, educator/tests/Test/Dscp/DB/SQLite/Real/Mode.hs, educator/tests/Test/Dscp/DB/SQLite/Real/Persistency.hs, educator/tests/Test/Dscp/DB/SQLite/Real/Transactions.hs
:man_shrugging: 
https://issues.serokell.io/issue/DSCP-386
=> [DSCP-386] Add a test on persistency of Educator's data

scripts/launch/node.sh
Hotfix to use the correct command syntax for `dscp-keygen`
No YT issue
=> hotfix: fix node to use dscp-keygen correctly

core/src/Dscp/Core/Aeson.hs, core/src/Dscp/Core/FairCV.hs, specs/disciplina/witness/api/witness.yaml, witness/src/Dscp/Witness/Web/Logic.hs, witness/tests/Test/Dscp/Witness/Explorer/Explorer.hs
As it was previously discussed, we add a field to quickly ensure whether everything is valid or not.
https://issues.serokell.io/issue/DSCP-414
=> [DSCP-414] Add a "all valid" field in `FairCVCheckResult`

pkgs.nix
As part of the work done for DSCP-418, some changes were made to the closure. To maintain consistency, I'm repinning for Disciplina as well.
The only relevant thing to devs here is that we no longer use `all-cabal-hashes` so you no longer have to poke ops when your dependencies are too new.
https://issues.serokell.io/issue/DSCP-418
=> [DSCP-418] Repin `serokell-closure`

educator/src/Dscp/Educator/Web/Logic.hs, witness/src/Dscp/Snowdrop/Actions.hs, witness/src/Dscp/Snowdrop/Configuration.hs, witness/src/Dscp/Snowdrop/Mode.hs, witness/src/Dscp/Snowdrop/ReadMode.hs, witness/src/Dscp/Witness/Logic/Apply.hs, witness/src/Dscp/Witness/Logic/Getters.hs, witness/src/Dscp/Witness/Mempool/Logic.hs, witness/src/Dscp/Witness/Mempool/Type.hs, witness/src/Dscp/Witness/Web/Logic.hs, witness/src/Dscp/Witness/Web/Types.hs, witness/tests/Test/Dscp/Witness/Explorer/Explorer.hs, witness/tests/Test/Dscp/Witness/Explorer/ExplorerSpec.hs
Previously we had separate processing for data stored in AVL and all other data.
They both were considered simultaneously only when necessary, i.e. in block application
and mempool modification.
Problem: this does not provide a reasonable level of abstraction, allowing for subtle bugs.
Solution: quick observation of blockchain-util's code has shown that composition of
actions on storages deliver an about-zero overhead (O(log (prefixes number))),
thus it makes sense to provide an interface which hides exact storage being accessed.
https://issues.serokell.io/issue/DSCP-367
- …
=> [DSCP-367] Merge `runSdM` and `runStateSdM`

multi-educator/package.yaml
Otherwise on each build I get 
```
Warning: /home/martoon/serokell/disciplina/multi-educator/package.yaml:
Ignoring unrecognized field
$.library.tests
```
which is annoying.
Generally, the problem is, `tests` section is part of `library` section while it should be a standalone property, but since multi-educator actually has no tests, I just remove test section entirely.
https://issues.serokell.io/issue/DSCP-
=> [SRK-8] Remove warning in package.yaml of multieducator

core/package.yaml, core/src/Dscp/Resource/AppDir.hs, core/src/Dscp/Resource/Functions.hs, core/src/Dscp/System/Other.hs, witness/src/Dscp/Witness/Launcher/Entry.hs
Show in witness, (multi-)educator & faucet.
Looks like:
https://issues.serokell.io/issue/DSCP-342
=> [DSCP-342] Show git revision at startup

core/src/Dscp/Util/Test.hs, educator/src/Dscp/DB/SQLite/Functions.hs, educator/src/Dscp/DB/SQLite/Util.hs, educator/src/Dscp/Educator/DB/DSL/Interpret/Sqlite3.hs, educator/src/Dscp/Educator/DB/Queries.hs, educator/src/Dscp/Educator/Logic/Publishing.hs, educator/src/Dscp/Educator/Web/Bot/Setting.hs, educator/src/Dscp/Educator/Web/Educator/Handlers.hs, educator/src/Dscp/Educator/Web/Educator/Queries.hs, educator/src/Dscp/Educator/Web/Logic.hs, educator/src/Dscp/Educator/Web/Queries.hs, educator/src/Dscp/Educator/Web/Server.hs, educator/src/Dscp/Educator/Web/Student/Queries.hs, educator/src/Dscp/Educator/Web/Types.hs, educator/tests/Test/Dscp/DB/SQLite/Queries.hs, educator/tests/Test/Dscp/DB/SQLite/Real/Transactions.hs, educator/tests/Test/Dscp/Educator/Mode.hs, educator/tests/Test/Dscp/Educator/Web/Educator/Queries.hs, educator/tests/Test/Dscp/Educator/Web/Scenarios.hs, educator/tests/Test/Dscp/Educator/Web/Student/Queries.hs
This is an ~exact revert of DisciplinaOU/disciplina#335.
Motivation:
* I need `instance MonadCatch` in database endpoints, and that's problematic to achieve in `Pg` monad which is `MonadBeam` implementation in Postgres case.
* `Pg`'s `>>=` does not execute SQL requests, rather collects them for execution in `Pg` runner. That's an inconvenient property for database endpoint monad, it complicates debugging.
* Previously mentioned reasons, like the fact that we carry context explicitly now (and we always carry it explicitly in tests).
=> Revert "[DSCP-406] Remove DBT"

release.nix
This is required to make it possible to use `disciplinta-tools` (in particular, `dscp-keygen` during deployment.
https://issues.serokell.io/issue/OPS-623
=> release.nix: Export disciplina-tools

default.nix, educator/tests/Test/Dscp/Educator/Web/Educator/Queries.hs, educator/tests/Test/Dscp/Educator/Web/Relations.hs
Add tests for `student-course` and `student-assignment` relations.
https://issues.serokell.io/issue/DSCP-433
=> [DSCP-433] Add relation tests for Educator API

core/src/Dscp/Core/Aeson.hs, core/src/Dscp/Core/Genesis.hs, core/src/Dscp/Core/Governance.hs, core/src/Dscp/Core/Slotting.hs, core/src/Dscp/Crypto/MerkleTree.hs, core/src/Dscp/Util.hs, educator/src/Dscp/Educator/DB/Queries.hs, faucet/src/Dscp/Faucet/Web/Logic.hs, hpack/definitions.yaml, witness/src/Dscp/Snowdrop/Expanders.hs, witness/src/Dscp/Snowdrop/Storage/PluginBased.hs, witness/src/Dscp/Web/Class.hs
Adds some useful warnings, one per commit.
The most arguable one IMO is `-Wincomplete-uni-patterns`. I find it generally good, in particular, because now I can safely add constructors to datatypes without being afraid of breaking any pattern-matches in lamdas and `let`s. The price is - this makes us explicitly throw errors in several places where incomplete patterns fit the best thus making the code ugly.
I removed `GovOpen` constructor because it's effectively not supported anyway.
https://issues.serokell.io/issue/DSCP-439
- [Swagger](../tree/master/specs/disciplina) API …
=> [DSCP-439] Advanced warnings

README.md, educator/src/Dscp/Educator/Web/Bot/Handlers.hs, educator/src/Dscp/Educator/Web/Educator/API.hs, educator/src/Dscp/Educator/Web/Educator/Handlers.hs, educator/src/Dscp/Educator/Web/Educator/Queries.hs, educator/src/Dscp/Educator/Web/Student/API.hs, educator/src/Dscp/Educator/Web/Student/Handlers.hs, educator/src/Dscp/Educator/Web/Student/Queries.hs, educator/tests/Test/Dscp/Educator/Bot/Endpoints.hs, educator/tests/Test/Dscp/Educator/Web/Educator/Queries.hs, educator/tests/Test/Dscp/Educator/Web/Student/Queries.hs, specs/disciplina/educator/api/educator.yaml, specs/disciplina/educator/api/student.yaml, stack.yaml, tools/package.yaml, tools/src/faircv/Client.hs
Endpoints like `getCourses`, `getAssignments` and `getSubmissions` now use pagination.
Endpoints like `getProofs` and `getGrades` left intact because in their case
keyset pagination fits better (new entries may appear without actions from client side),
and this pagination is not yet implemented.
**Do not merge** before dependency not on `master` of `servant-util` is fixed.
https://issues.serokell.io/issue/DSCP-143
=> [DSCP-143] Introduce pagination to Student and Educator APIs

stack.yaml
So that it depends on `master`.
After all sufferings, I took to make CI work I forgot to merge the `servant-util`'s branch with pagination to master.
https://issues.serokell.io/issue/DSCP-143
=> [DSCP-143] Fix dependency on servant-util :(

educator/src/Dscp/Educator/Web/Auth.hs, educator/src/Dscp/Educator/Web/Bot/Handlers.hs, educator/src/Dscp/Educator/Web/Server.hs, educator/src/Dscp/Educator/Web/Student/Auth.hs, educator/tests/Test/Dscp/Educator/Bot/Endpoints.hs
Instead of modifying each bot endpoint to register new students, we'd better do that
in authentication hook.
I'm not sure which kind of tests should be written here.
I didn't test this PR yet even manually since I can't remove `--student-api-no-auth` flag (need to fix that one day).
https://issues.serokell.io/issue/DSCP-289
=> [DSCP-289] Prepare student initial settings in auth hook

pdfs/src/Pdf/Scanner.hs
Fixing PDF generator and injector not working together.
https://issues.serokell.io/issue/DSCP-483
=> [DSCP-483] Moved insertion point to before startxref

docs/config-full-sample.yaml, educator/src/Dscp/Educator/CLI.hs, multi-educator/src/Dscp/MultiEducator/CLI.hs, multi-educator/src/Dscp/MultiEducator/Config.hs, multi-educator/src/Dscp/MultiEducator/Launcher/Mode.hs, multi-educator/src/Dscp/MultiEducator/Web/Educator/API.hs, multi-educator/src/Dscp/MultiEducator/Web/Educator/Auth.hs, multi-educator/src/Dscp/MultiEducator/Web/Server.hs, scripts/launch/node.sh
Allows optional authentication AND enables logging (sorre, otherwise that would take too long). Only 2 commits.
I made multi-educator authentication return `EducatorAuthData` instead of `EducatorAuthToken` because the latter mainly contains (aside from `EducatorAuthData` itself) auth implementation details unneeded for endpoints implementation.
https://issues.serokell.io/issue/DSCP-474
=> [DSCP-474] Optional multi auth

specs/disciplina/educator/api/educator.yaml
When I implemented auto-swagger, I somehow managed to remove some parts of Educator API
swagger spec :facepalm:
https://issues.serokell.io/issue/DSCP-467
=> [DSCP-467] Return deleted stuff from educator.yaml swagger

core/src/Dscp/Resource/AppDir.hs, educator/src/Dscp/Educator/Launcher/Resource.hs, educator/tests/Test/Dscp/Educator/Mode.hs, multi-educator/package.yaml, multi-educator/src/Dscp/MultiEducator/Launcher/Mode.hs, multi-educator/src/Dscp/MultiEducator/Launcher/Resource.hs, witness/src/Dscp/Resource/Keys/Functions.hs, witness/src/Dscp/Witness/Launcher/Context.hs, witness/tests/Test/Dscp/Witness/Mode.hs
Adds multi-educator workers and a bit of cleanup.
Review on a per-commit basis is recommended.
Tested with optional authentication and no fees, when I add a certificate a private block is published and gets visible in explorer.
https://issues.serokell.io/issue/DSCP-485
=> [DSCP-485] Multi educator workers

witness/src/Dscp/Witness/Web/Logic.hs
With the current one we cannot even verify certificates with just 3 grades.
Sane limits are to be set in DSCP-495 later.
https://issues.serokell.io/issue/DSCP-495
=> [DSCP-495] Remove limit in `checkFairCVPDF`

config.yaml, core/src/Dscp/Core/Foundation/Educator.hs, educator/package.yaml, educator/src/Dscp/Educator/Web/Educator/API.hs, educator/src/Dscp/Educator/Web/Educator/Queries.hs, educator/src/Dscp/Educator/Web/Educator/Swagger.hs, educator/src/Dscp/Educator/Web/Server.hs, educator/src/Dscp/Educator/Web/Student/API.hs, educator/src/Dscp/Educator/Web/Student/Queries.hs, educator/src/Dscp/Educator/Web/Student/Swagger.hs, educator/tests/Test/Dscp/Educator/Web/Educator/Swagger.hs, educator/tests/Test/Dscp/Educator/Web/Student/Swagger.hs, multi-educator/package.yaml, multi-educator/src/Dscp/MultiEducator/Launcher/Mode.hs, multi-educator/src/Dscp/MultiEducator/Launcher/Resource.hs, multi-educator/src/Dscp/MultiEducator/Types.hs, multi-educator/src/Dscp/MultiEducator/Web/Educator/API.hs, multi-educator/src/Dscp/MultiEducator/Web/Educator/Auth.hs, multi-educator/src/Dscp/MultiEducator/Web/Educator/Handlers.hs, multi-educator/src/Dscp/MultiEducator/Web/Server.hs, multi-educator/src/Dscp/MultiEducator/Web/Swagger.hs, stack.yaml, tools/package.yaml, tools/src/swagger/Main.hs, tools/src/swagger/SwaggerOptions.hs, witness/package.yaml, witness/src/Dscp/Web/Swagger/Generation/Global.hs, witness/src/Dscp/Web/Swagger/Instances/Core.hs, witness/src/Dscp/Web/Swagger/UI.hs, witness/src/Dscp/Web/Types.hs
Serve swagger UI next to our main endpoints.
I also had to add swagger generation to multi-educator and slightly rearrange API types and server implementations.
Finally, I bumped the version of `servant-util` so sorting has to be updated.
https://issues.serokell.io/issue/DSCP-473
=> [DSCP-473] Swagger UI
